import 'models.dart';

class BibliaDados {
  static final List<LivroBiblico> livrosBiblicos = [
    // at
    LivroBiblico(
      id: 'genesis',
      nome: 'Gênesis',
      testamento: 'Antigo',
      capitulos: 50,
    ),
    LivroBiblico(
      id: 'exodo',
      nome: 'Êxodo',
      testamento: 'Antigo',
      capitulos: 40,
    ),
    LivroBiblico(
      id: 'levitico',
      nome: 'Levítico',
      testamento: 'Antigo',
      capitulos: 27,
    ),
    LivroBiblico(
      id: 'numeros',
      nome: 'Números',
      testamento: 'Antigo',
      capitulos: 36,
    ),
    LivroBiblico(
      id: 'deuteronomio',
      nome: 'Deuteronômio',
      testamento: 'Antigo',
      capitulos: 34,
    ),
    LivroBiblico(
      id: 'josue',
      nome: 'Josué',
      testamento: 'Antigo',
      capitulos: 24,
    ),
    LivroBiblico(
      id: 'juizes',
      nome: 'Juízes',
      testamento: 'Antigo',
      capitulos: 21,
    ),
    LivroBiblico(id: 'rute', nome: 'Rute', testamento: 'Antigo', capitulos: 4),
    LivroBiblico(
      id: '1samuel',
      nome: '1 Samuel',
      testamento: 'Antigo',
      capitulos: 31,
    ),
    LivroBiblico(
      id: '2samuel',
      nome: '2 Samuel',
      testamento: 'Antigo',
      capitulos: 24,
    ),
    LivroBiblico(
      id: '1reis',
      nome: '1 Reis',
      testamento: 'Antigo',
      capitulos: 22,
    ),
    LivroBiblico(
      id: '2reis',
      nome: '2 Reis',
      testamento: 'Antigo',
      capitulos: 25,
    ),
    LivroBiblico(
      id: '1cronicas',
      nome: '1 Crônicas',
      testamento: 'Antigo',
      capitulos: 29,
    ),
    LivroBiblico(
      id: '2cronicas',
      nome: '2 Crônicas',
      testamento: 'Antigo',
      capitulos: 36,
    ),
    LivroBiblico(
      id: 'esdras',
      nome: 'Esdras',
      testamento: 'Antigo',
      capitulos: 10,
    ),
    LivroBiblico(
      id: 'neemias',
      nome: 'Neemias',
      testamento: 'Antigo',
      capitulos: 13,
    ),
    LivroBiblico(
      id: 'ester',
      nome: 'Ester',
      testamento: 'Antigo',
      capitulos: 10,
    ),
    LivroBiblico(id: 'jo', nome: 'Jó', testamento: 'Antigo', capitulos: 42),
    LivroBiblico(
      id: 'salmos',
      nome: 'Salmos',
      testamento: 'Antigo',
      capitulos: 150,
    ),
    LivroBiblico(
      id: 'proverbios',
      nome: 'Provérbios',
      testamento: 'Antigo',
      capitulos: 31,
    ),
    LivroBiblico(
      id: 'eclesiastes',
      nome: 'Eclesiastes',
      testamento: 'Antigo',
      capitulos: 12,
    ),
    LivroBiblico(
      id: 'cantares',
      nome: 'Cantares',
      testamento: 'Antigo',
      capitulos: 8,
    ),
    LivroBiblico(
      id: 'isaias',
      nome: 'Isaías',
      testamento: 'Antigo',
      capitulos: 66,
    ),
    LivroBiblico(
      id: 'jeremias',
      nome: 'Jeremias',
      testamento: 'Antigo',
      capitulos: 52,
    ),
    LivroBiblico(
      id: 'lamentacoes',
      nome: 'Lamentações',
      testamento: 'Antigo',
      capitulos: 5,
    ),
    LivroBiblico(
      id: 'ezequiel',
      nome: 'Ezequiel',
      testamento: 'Antigo',
      capitulos: 48,
    ),
    LivroBiblico(
      id: 'daniel',
      nome: 'Daniel',
      testamento: 'Antigo',
      capitulos: 12,
    ),
    LivroBiblico(
      id: 'oseias',
      nome: 'Oséias',
      testamento: 'Antigo',
      capitulos: 14,
    ),
    LivroBiblico(id: 'joel', nome: 'Joel', testamento: 'Antigo', capitulos: 3),
    LivroBiblico(id: 'amos', nome: 'Amós', testamento: 'Antigo', capitulos: 9),
    LivroBiblico(
      id: 'obadias',
      nome: 'Obadias',
      testamento: 'Antigo',
      capitulos: 1,
    ),
    LivroBiblico(
      id: 'jonas',
      nome: 'Jonas',
      testamento: 'Antigo',
      capitulos: 4,
    ),
    LivroBiblico(
      id: 'miqueias',
      nome: 'Miquéias',
      testamento: 'Antigo',
      capitulos: 7,
    ),
    LivroBiblico(id: 'naum', nome: 'Naum', testamento: 'Antigo', capitulos: 3),
    LivroBiblico(
      id: 'habacuque',
      nome: 'Habacuque',
      testamento: 'Antigo',
      capitulos: 3,
    ),
    LivroBiblico(
      id: 'sofonias',
      nome: 'Sofonias',
      testamento: 'Antigo',
      capitulos: 3,
    ),
    LivroBiblico(id: 'ageu', nome: 'Ageu', testamento: 'Antigo', capitulos: 2),
    LivroBiblico(
      id: 'zacarias',
      nome: 'Zacarias',
      testamento: 'Antigo',
      capitulos: 14,
    ),
    LivroBiblico(
      id: 'malaquias',
      nome: 'Malaquias',
      testamento: 'Antigo',
      capitulos: 4,
    ),

    // nt
    LivroBiblico(
      id: 'mateus',
      nome: 'Mateus',
      testamento: 'Novo',
      capitulos: 28,
    ),
    LivroBiblico(
      id: 'marcos',
      nome: 'Marcos',
      testamento: 'Novo',
      capitulos: 16,
    ),
    LivroBiblico(id: 'lucas', nome: 'Lucas', testamento: 'Novo', capitulos: 24),
    LivroBiblico(id: 'joao', nome: 'João', testamento: 'Novo', capitulos: 21),
    LivroBiblico(id: 'atos', nome: 'Atos', testamento: 'Novo', capitulos: 28),
    LivroBiblico(
      id: 'romanos',
      nome: 'Romanos',
      testamento: 'Novo',
      capitulos: 16,
    ),
    LivroBiblico(
      id: '1corintios',
      nome: '1 Coríntios',
      testamento: 'Novo',
      capitulos: 16,
    ),
    LivroBiblico(
      id: '2corintios',
      nome: '2 Coríntios',
      testamento: 'Novo',
      capitulos: 13,
    ),
    LivroBiblico(
      id: 'galatas',
      nome: 'Gálatas',
      testamento: 'Novo',
      capitulos: 6,
    ),
    LivroBiblico(
      id: 'efesios',
      nome: 'Efésios',
      testamento: 'Novo',
      capitulos: 6,
    ),
    LivroBiblico(
      id: 'filipenses',
      nome: 'Filipenses',
      testamento: 'Novo',
      capitulos: 4,
    ),
    LivroBiblico(
      id: 'colossenses',
      nome: 'Colossenses',
      testamento: 'Novo',
      capitulos: 4,
    ),
    LivroBiblico(
      id: '1tessalonicenses',
      nome: '1 Tessalonicenses',
      testamento: 'Novo',
      capitulos: 5,
    ),
    LivroBiblico(
      id: '2tessalonicenses',
      nome: '2 Tessalonicenses',
      testamento: 'Novo',
      capitulos: 3,
    ),
    LivroBiblico(
      id: '1timoteo',
      nome: '1 Timóteo',
      testamento: 'Novo',
      capitulos: 6,
    ),
    LivroBiblico(
      id: '2timoteo',
      nome: '2 Timóteo',
      testamento: 'Novo',
      capitulos: 4,
    ),
    LivroBiblico(id: 'tito', nome: 'Tito', testamento: 'Novo', capitulos: 3),
    LivroBiblico(
      id: 'filemom',
      nome: 'Filemom',
      testamento: 'Novo',
      capitulos: 1,
    ),
    LivroBiblico(
      id: 'hebreus',
      nome: 'Hebreus',
      testamento: 'Novo',
      capitulos: 13,
    ),
    LivroBiblico(id: 'tiago', nome: 'Tiago', testamento: 'Novo', capitulos: 5),
    LivroBiblico(
      id: '1pedro',
      nome: '1 Pedro',
      testamento: 'Novo',
      capitulos: 5,
    ),
    LivroBiblico(
      id: '2pedro',
      nome: '2 Pedro',
      testamento: 'Novo',
      capitulos: 3,
    ),
    LivroBiblico(id: '1joao', nome: '1 João', testamento: 'Novo', capitulos: 5),
    LivroBiblico(id: '2joao', nome: '2 João', testamento: 'Novo', capitulos: 1),
    LivroBiblico(id: '3joao', nome: '3 João', testamento: 'Novo', capitulos: 1),
    LivroBiblico(id: 'judas', nome: 'Judas', testamento: 'Novo', capitulos: 1),
    LivroBiblico(
      id: 'apocalipse',
      nome: 'Apocalipse',
      testamento: 'Novo',
      capitulos: 22,
    ),
  ];
}
